version: '3'

services:
  db:
    container_name: knex_demo
    image: postgres:14.2
    environment:
      PGUSER: "knex" #Variável pré-definir o usuário da ferramenta psql.
      POSTGRES_USER: "knex"
      POSTGRES_PASSWORD: "knex@passwd"
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data 